### ISSUE TITLE
NMON Portals not opening

### ISSUE THREAD

**Issue by SergeyKuzmitskiy** [axibase/atsd#322]
Hello,

I installed latest version of Axibase. When I try to Open AIX or Linux Portal blank page is displayed. I uploaded some data to AIX nmon, Linux nmon is empty now. In ATSD log I see Java errors:
`2017-11-27 20:10:02,587;ERROR;qtp1140132862-192;com.axibase.tsd.web.portal.PortalFileController;Unexpected error
java.lang.NullPointerException: null
        at com.axibase.tsd.service.freemarker.LastInsertTimeMethod.exec(LastInsertTimeMethod.java:34) ~[atsd.17988.jar:na]
        at freemarker.core.MethodCall._eval(MethodCall.java:65) ~[atsd.17988.jar:na]
        at freemarker.core.Expression.eval(Expression.java:81) ~[atsd.17988.jar:na]
        at freemarker.core.DefaultToExpression._eval(DefaultToExpression.java:89) ~[atsd.17988.jar:na]
        at freemarker.core.Expression.eval(Expression.java:81) ~[atsd.17988.jar:na]
        at freemarker.core.Assignment.accept(Assignment.java:134) ~[atsd.17988.jar:na]
        at freemarker.core.Environment.visit(Environment.java:327) ~[atsd.17988.jar:na]
        at freemarker.core.Environment.visit(Environment.java:333) ~[atsd.17988.jar:na]
        at freemarker.core.Environment.process(Environment.java:306) ~[atsd.17988.jar:na]
        at freemarker.template.Template.process(Template.java:386) ~[atsd.17988.jar:na]
        at com.axibase.tsd.service.freemarker.FreeMarkerServiceImpl.evaluateNoCache(FreeMarkerServiceImpl.java:66) ~[atsd.17988.jar:na]
        at com.axibase.tsd.web.portal.PortalFileController.handleFile(PortalFileController.java:58) ~[atsd.17988.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [atsd.17988.jar:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [atsd.17988.jar:na]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [atsd.17988.jar:na]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [atsd.17988.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [atsd.17988.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [atsd.17988.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) [atsd.17988.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [atsd.17988.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) [atsd.17988.jar:na]
        at com.axibase.tsd.service.monitoring.SimonServletFilterFixed.doFilterWithMonitoring(SimonServletFilterFixed.java:229) [atsd.17988.jar:na]
        at com.axibase.tsd.service.monitoring.SimonServletFilterFixed.doFilter(SimonServletFilterFixed.java:214) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.switchuser.SwitchUserFilter.doFilter(SwitchUserFilter.java:181) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [atsd.17988.jar:na]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) [atsd.17988.jar:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [atsd.17988.jar:na]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [atsd.17988.jar:na]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [atsd.17988.jar:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:294) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:370) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [atsd.17988.jar:na]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [atsd.17988.jar:na]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [atsd.17988.jar:na]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [atsd.17988.jar:na]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [atsd.17988.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [atsd.17988.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [atsd.17988.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2017-11-27 20:10:02,764;ERROR;qtp1140132862-191;com.axibase.tsd.web.portal.PortalFileController;Unexpected error
java.lang.NullPointerException: null
        at com.axibase.tsd.service.freemarker.LastInsertTimeMethod.exec(LastInsertTimeMethod.java:34) ~[atsd.17988.jar:na]
        at freemarker.core.MethodCall._eval(MethodCall.java:65) ~[atsd.17988.jar:na]
        at freemarker.core.Expression.eval(Expression.java:81) ~[atsd.17988.jar:na]
        at freemarker.core.DefaultToExpression._eval(DefaultToExpression.java:89) ~[atsd.17988.jar:na]
        at freemarker.core.Expression.eval(Expression.java:81) ~[atsd.17988.jar:na]
        at freemarker.core.Assignment.accept(Assignment.java:134) ~[atsd.17988.jar:na]
        at freemarker.core.Environment.visit(Environment.java:327) ~[atsd.17988.jar:na]
        at freemarker.core.Environment.visit(Environment.java:333) ~[atsd.17988.jar:na]
        at freemarker.core.Environment.process(Environment.java:306) ~[atsd.17988.jar:na]
        at freemarker.template.Template.process(Template.java:386) ~[atsd.17988.jar:na]
        at com.axibase.tsd.service.freemarker.FreeMarkerServiceImpl.evaluateNoCache(FreeMarkerServiceImpl.java:66) ~[atsd.17988.jar:na]
        at com.axibase.tsd.web.portal.PortalFileController.handleFile(PortalFileController.java:58) ~[atsd.17988.jar:na]
        at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [atsd.17988.jar:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [atsd.17988.jar:na]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [atsd.17988.jar:na]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [atsd.17988.jar:na]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [atsd.17988.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [atsd.17988.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [atsd.17988.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) [atsd.17988.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [atsd.17988.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496) [atsd.17988.jar:na]
        at com.axibase.tsd.service.monitoring.SimonServletFilterFixed.doFilterWithMonitoring(SimonServletFilterFixed.java:229) [atsd.17988.jar:na]
        at com.axibase.tsd.service.monitoring.SimonServletFilterFixed.doFilter(SimonServletFilterFixed.java:214) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.switchuser.SwitchUserFilter.doFilter(SwitchUserFilter.java:181) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [atsd.17988.jar:na]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) [atsd.17988.jar:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [atsd.17988.jar:na]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [atsd.17988.jar:na]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [atsd.17988.jar:na]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [atsd.17988.jar:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:294) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [atsd.17988.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:370) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [atsd.17988.jar:na]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [atsd.17988.jar:na]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [atsd.17988.jar:na]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [atsd.17988.jar:na]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) [atsd.17988.jar:na]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) [atsd.17988.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [atsd.17988.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [atsd.17988.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
`

**Comment by rodionos** [comment]
Greetings!

Do you observe the same error if you the open portal via the url `https://atsd_hostname:8443/portal/name/AIX%20nmon?entity=aix03`?

> Replace `aix003` with the actual hostname of the LPAR in the link above.

I can reproduce this error only the entity is missing in the URL. 
The AIX and Linux nmon portals are [template](https://github.com/axibase/atsd/blob/master/portals/creating-and-assigning-portals.md) portals so they need an entity name as a parameter.

Regards,

Sergei

**Comment by SergeyKuzmitskiy** [comment]
Yep, I used your link, it working now.

So portals should be referenced only from entity page. That was not obvious for me.

Many thanks for your help.

**Comment by rodionos** [comment]
Yes, this type of portal is re-usable but it needs an lpar name (entity parameter) to load the data.
The template portals can be launched in the entity editor, but also from the entity list.

Here's how - click on the Entities tab in the left menu, select `nmon-aix` entity group. If it's not enabled in your installation, open the Settings link in the left menu, open the Entities Groups page and change it's status to enabled. Once the group is enabled, it will appear in the drop-down on the Entities page.
The group will list all AIX systems, and the portals link will be displayed on the left.

![aix-portal](https://user-images.githubusercontent.com/2098022/33291465-f1fa5494-d3d6-11e7-90db-8e5e6eefb4f1.png)

You can also create a custom entity view for your instance so that your LPARs and their key metrics are accessible from the left menu. Click on Entity Views link in the left menu, select Configure, import the attached [aix_ev.xml](https://github.com/axibase/atsd/files/1507752/aix_ev.txt) (rename it from txt to xml as github doesn't support xml file type in issue attachments). The aix entity view will look as follows:

![portal_link](https://user-images.githubusercontent.com/2098022/33291741-ee4bfcca-d3d7-11e7-865f-dfb8c5ad42c1.png)
